{
 "title": "Beta-KPI-Calc-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Power Drive KPI Dashboard\n\n## Designed to have an overview about the drives in the factory line\n### Customer Dashboard\n\n\n\n\n\n"
   }
  },
  { "title": "CET Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Data Flow",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Drive value counts",
   "type": "grafana-piechart-panel",
   "description": "Available - Drive data in the InfluxDB",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "currentdrive3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltagedrive1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperatur2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 } },
  {
   "title": "PowerDrive2 - KPI",
   "type": "graph",
   "description": "KPI (Mean,Median,Standard dev) calculation for the PowerDrive2",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Watt" }
   ],
   "targets": [
    {
     "measurement": "POWERDRIVE2_STANDARD_KPIS",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ],
      [
       { "params": [ "median" ], "type": "field" }
      ],
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Drive List",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "measurement": "POWERDRIVE2_STANDARD_KPIS",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "mean" ], "type": "field" }
      ],
      [
       { "params": [ "median" ], "type": "field" }
      ],
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "POWERDRIVE1_STANDARD_KPIS",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "mean" ], "type": "field" }
      ],
      [
       { "params": [ "median" ], "type": "field" }
      ],
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PowerDrive3 - Mean",
   "type": "stat",
   "description": "Sliding Mean of Powerdrive3. The sliding window can vary and can be changed on the fly",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "POWERDRIVE3_MEAN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}